### ISSUE TITLE
make nebu be able to be found in diffrent ways outher than just mineing

### ISSUE THREAD

**Issue by Guineapigboyx** [uthw/minecraft-modpack#11]
tho make it in a way mining would not just be outclassed entirely. since finding the nebu after looking for a long time is kind the highlight of the dimension

**Comment by uthw** [comment]
natural generation of nebu ore has been doubled in 47d3acf. later I will add nebu to loot containers in atum. Do you have an idea of where else nebu could be found?

**Comment by Guineapigboyx** [comment]
You should be able to craft a nebu drop or inget if you get all five of the vanity items in the relic ore. OR you could make it so of you get 4 or 9 of them you can get one.

I think something with the dusty bones might be a good idea

**Comment by uthw** [comment]
added a recipe for nebu ingots using relics in 3171b3f
