### ISSUE TITLE
Remove baby Mobs they are just not fun

### ISSUE THREAD

**Issue by Guineapigboyx** [uthw/minecraft-modpack#12]
I don't care what mod they are on they just suck all the way never had a good time with them

baby enemies are unbalanced in gameplay. baby zombies are far too common as they destroy you very quickly as well as baby skeletons shooting way too quickly. all baby enemies spawn far too frequently as well.

**Comment by uthw** [comment]
Fixed by making baby skeletons (and strays) much less common in a36d59f
