### ISSUE TITLE
The godforge mechanic in the atum is to expensive

### ISSUE THREAD

**Issue by Guineapigboyx** [uthw/minecraft-modpack#23]
Currently to even get 1 godforge block to just get one artifact takes a lot of nebu. What nebu also just so happens to also be the same very rare material you need for the main quest line inside of the atum.

There's a few ways. I think you could fix. You could make it be a post pharaoh thing and not take nebu. Or make nebu easier to get after you already have gotten some.

**Comment by uthw** [comment]
Fixed by making nebu more common in [47d3acf](https://github.com/uthw/minecraft-modpack/commit/47d3acf46eaceba3bf5836b2bdf2495288e11fbb).
