### ISSUE TITLE
artifical golum need to be nerfed

### ISSUE THREAD

**Issue by Guineapigboyx** [uthw/minecraft-modpack#27]
summoner golems

mainly lower the HP that's mostly it
you can also consider getting rid of the ability for them to be bosses but then that gets rid of one of the benefits of fighting to summoner since you will not get enchanted books anymore. _if you can just make it so they have to be weak bosses_

**Comment by Guineapigboyx** [comment]
also one of the bosses hit sent me out of the arena once.
by that I mean one had knockback and one head levitating and I kept getting it making me go up until they clipped me out of the arena.

**Comment by uthw** [comment]
Fixed in 4990367 - artificial golems (and mummies from Atum) can no longer spawn as bosses
