### ISSUE TITLE
confuseing hammer quests for tetra

### ISSUE THREAD

**Issue by Guineapigboyx** [uthw/minecraft-modpack#34]
First of all, it starts at hammer 4 which is the Blackstone hammer and is level 4 what 1 more than iron hammer. then it says to geta an obsidian hammer but to get that you need a hammer an level 6.

**Comment by uthw** [comment]
You need the forge hammer, which is in the tetra quests

Edit: You can also craft it if you've done create

**Comment by Guineapigboyx** [comment]
Make sure you make that cleat you can.
I have not checked in 21 if you did that already
