### ISSUE TITLE
OP trinkets

### ISSUE THREAD

**Issue by Guineapigboyx** [uthw/minecraft-modpack#36]
Tha ghost is the worst in my opinion it makes it so no mobs can see you
Lunch Bag is also very OP it gives you sattuation

Maybe the Bat but it is more nice to have than anything

**Comment by uthw** [comment]
Removed lunch bag and octopus leg in [e349093](https://github.com/uthw/minecraft-modpack/commit/e349093b5ae23a004f0f4489e1448f8c20c4d3e7)
