### ISSUE TITLE
multiple quests broke

### ISSUE THREAD

**Issue by Guineapigboyx** [uthw/minecraft-modpack#37]
to name some

- Soul black simth 
- Ice maze
- Wrought chamber
- blazing core (possibly other spell stones

there is more i just don't know them off the top of my head

**Comment by uthw** [comment]
Fixed nether quests in [5bf7a6a](https://github.com/uthw/minecraft-modpack/commit/5bf7a6a406bcfd732142fa8e96c1922267a40703). "battles" chapter has been removed I guess that fixes it?
