### ISSUE TITLE
Netherite monstrosity to easy

### ISSUE THREAD

**Issue by Guineapigboyx** [uthw/minecraft-modpack#38]
when compared with some other bosses like the Ice Maze boss it is super easy.
tho I don't know if this had to do with the gear I had since I had super good gear for the stage of the game I'm in.
also I was 2000 blocks out he was a walk in the park

**Comment by uthw** [comment]
Monstrosity's HP has been doubled and damage increased in [b3df31f](https://github.com/uthw/minecraft-modpack/commit/b3df31f89e7769dddbebdea4be2fd8bf2b202243)
