### ISSUE TITLE
tomb stonemod not auto equiping gear

### ISSUE THREAD

**Issue by Guineapigboyx** [uthw/minecraft-modpack#41]
This one is really want to be fixed

**Comment by Guineapigboyx** [comment]
by the way, I was able to determine that it was a new mod or some kube js thing.

since both 20 and 21 use the same version of corral tombstone

**Comment by uthw** [comment]
Was this a problem in v20 or below?

**Comment by Guineapigboyx** [comment]
No new issue this version
It happens everytime.
Also I did check auto Equip was on always

**Comment by uthw** [comment]
Happens to me as well, I'll see what I can do

**Comment by uthw** [comment]
Has it been ever since 0.21 or did it start with 0.21.1 or 2?
