### ISSUE TITLE
Why is honeycombs a requiremnet for agriculture

### ISSUE THREAD

**Issue by Guineapigboyx** [uthw/minecraft-modpack#43]
I understand why you made a bee quest line. but why is it the first quest in the whole agriculture questline tree.

**Comment by uthw** [comment]
Bees play a big role in resource production using agriculture. It's important we know how vanilla beehives work, since not everyone does

Btw this is a better question to ask me in discord since it isn't really an issue

**Comment by Guineapigboyx** [comment]
All what I was trying to say was to do the quest after the campfire what involves you getting a honey comb you need to harvest honey from hives. Base game hives can't be found and the bee hives in trees do not work or it is not clear on how to get them to work if they could.
