### ISSUE TITLE
underutilied curio slots

### ISSUE THREAD

**Issue by Guineapigboyx** [uthw/minecraft-modpack#45]
It went from always having most of the slots. to never having anything in the slots

**Comment by uthw** [comment]
I'm guessing you're referring to Relic Ex  being removed, but can't be quite sure. Remember you haven't gotten past early game yet on v21, there will be items that come along for each slot

**Comment by Guineapigboyx** [comment]
Fair but I had at least 1/2 of my slots filled by blue skies. Usually by the end when I'm in the spider dungon I usually I have multiple of the most common slots like chest and neck, and most other slots filled
