### ISSUE TITLE
Parasites do way to much damage

### ISSUE THREAD

**Issue by Guineapigboyx** [uthw/minecraft-modpack#47]
I get 2 shots by them in less than 3 seconds with full iron in easy with 4 extra hearts.

_also getting almost insta killed by something out of your control feels unfair_

**Comment by uthw** [comment]
Yeah. Hostile mobs aren't completely balanced right now, some are super strong and some are pushovers.

I nerfed basically everything about the parasites for next subupdate.

**Comment by uthw** [comment]
b7b8b7b
