### ISSUE TITLE
normal running speed feels slow

### ISSUE THREAD

**Issue by Guineapigboyx** [uthw/minecraft-modpack#51]
now since better grappling hooks are harder to get early game distance travel is way harder and slower.

_this could be fixed by just making it so your ground running speed is faster_

**Comment by uthw** [comment]
Don't forget there are transportation options besides grappling hooks. Remember there are mobs that can be used for transport like horses and hippogryphs, there is the reusable ender pearl from Cyclic, the ender staff from Grapple mod, and other grappling hook upgrades like the Forcefield.

**Comment by Guineapigboyx** [comment]
that is fair. tho i can't even remember ever seeing a horse in mincemeat
