### ISSUE TITLE
Atum questline not starting if you only killed the Boss of blue skies

### ISSUE THREAD

**Issue by Guineapigboyx** [uthw/minecraft-modpack#7]
I killed the alchemist and then went for the Atum and the quest line did not start. if you are curious it looks like you need to get game Stage 3 to unlock the Atum quests but you can still go to the Atum even if you are at game Stage 2 What you get for killing the first Blue Skies boss and going onto the split of the second blue skis boss or Atum bosses.

**Comment by uthw** [comment]
Fixed in 29a59f3
